import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { chromium } from 'file:///C:/Users/omar4/AppData/Local/nvm/v20.20.2/node_modules/@playwright/cli/node_modules/playwright-core/index.mjs';
import { mockSessionPage } from './helpers/built-app.mjs';
const requireApp = createRequire(new URL('../package.json', import.meta.url));
const { createServer } = await import(pathToFileURL(requireApp.resolve('vite')).href);
const evidence = fileURLToPath(new URL('../../../scratch/shaheen-phase1/', import.meta.url));

test('Lab lifecycle, same-context transitions, quality, accessibility, input and fallback', { timeout: 120000 }, async () => {
  const server = await createServer({ configFile: fileURLToPath(new URL('../vite.config.ts', import.meta.url)), server: { host: '127.0.0.1', port: 0, strictPort: false, hmr: false }, logLevel: 'error' });
  await server.listen();
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    await mkdir(evidence, { recursive: true });
    const { context, page } = await mockSessionPage({ newContext: options => browser.newContext({ ...options, deviceScaleFactor: 2 }) });
    await page.setViewportSize({ width: 1440, height: 1100 });
    const cdp = await context.newCDPSession(page);

    await page.route('https://fonts.googleapis.com/**', route => route.fulfill({ status: 200, contentType: 'text/css', body: '' }));
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    const origin = server.resolvedUrls.local[0];
    await page.goto(origin + 'shaheen-lab');
    const orb = page.getByTestId('ai-hero-model');
    await page.waitForFunction(() => document.querySelector('.orb3d')?.dataset.ready === 'true');
    const canvas = await orb.locator('canvas').elementHandle();
    // Browser visibility event suspension, then re-entry without a second loop.
    await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); });
    const hiddenFrames = await orb.getAttribute('data-frame');
    await page.waitForTimeout(150);
    assert.equal(await orb.getAttribute('data-frame'), hiddenFrames);
    await page.evaluate(() => { delete document.hidden; document.dispatchEvent(new Event('visibilitychange')); });
    await page.waitForTimeout(100);
    assert.ok(Number(await orb.getAttribute('data-frame')) > Number(hiddenFrames));
    const report = {};
    for (const state of ['Idle', 'Thinking', 'Responding', 'Success', 'Warning', 'Error', 'Disabled']) {
      await page.getByRole('button', { name: state, exact: true }).click();
      await page.waitForTimeout(500);
      assert.equal(await orb.getAttribute('data-application-state'), state.toLowerCase());
      assert.ok(await canvas.evaluate(el => el === document.querySelector('.orb3d canvas')), 'same canvas on transition');
      await page.screenshot({ path: evidence + state.toLowerCase() + '.png' });
      report[state] = await page.locator('.lab-telemetry').innerText();
      if (state === 'Success' || state === 'Error') {
        await page.waitForFunction(() => document.querySelector('.orb3d')?.dataset.applicationState === 'idle');
      }
    }
    await page.getByRole('button', { name: 'Idle', exact: true }).click();
    for (const quality of ['low', 'medium', 'high']) {
      await page.getByLabel('Rendering Tier').selectOption(quality);
      assert.ok(await canvas.evaluate(el => el === document.querySelector('.orb3d canvas')));
      await page.waitForTimeout(1100);
      report[quality] = await page.locator('.lab-telemetry').innerText();
      await page.screenshot({ path: evidence + quality + '-quality.png' });
    }
    await page.getByLabel('Force Reduced Motion').check();
    await page.waitForTimeout(100);
    const frames = await orb.getAttribute('data-frame');
    await page.waitForTimeout(200);
    assert.equal(await orb.getAttribute('data-frame'), frames, 'reduced motion stops RAF');
    await page.screenshot({ path: evidence + 'reduced-motion.png' });
    await page.getByRole('button', { name: 'Thinking', exact: true }).click();
    await page.waitForTimeout(1100);
    assert.match(await page.locator('.lab-telemetry').innerText(), /1\.220/);
    await page.getByLabel('Force Reduced Motion').uncheck();
    await page.getByRole('button', { name: 'Idle', exact: true }).click();
    const hit = orb.getByRole('button', { name: 'Interactive 3D orb' });
    await hit.focus();
    for (const key of ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'q', 'e', 'r']) await page.keyboard.press(key);
    const box = await hit.boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 40, box.y + box.height / 2 - 30, { steps: 5 });
    assert.equal(await hit.getAttribute('data-dragging'), 'true');
    await page.mouse.up();
    assert.equal(await hit.getAttribute('data-dragging'), 'false');
    await page.getByLabel('Enable Drag Interaction').uncheck();
    assert.equal(await hit.getAttribute('aria-disabled'), 'true');
    await page.getByLabel('Enable Drag Interaction').check();
    await page.getByRole('button', { name: 'Reset Orientation' }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(200);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    assert.equal(await hit.evaluate(el => getComputedStyle(el).touchAction), 'none');
    assert.notEqual(await page.locator('.lab-stage').evaluate(el => getComputedStyle(el).touchAction), 'none');
    await page.screenshot({ path: evidence + 'mobile.png' });
    await hit.scrollIntoViewIfNeeded();
    const touchBox = await hit.boundingBox();
    const touchPoint = { x: touchBox.x + touchBox.width / 2, y: touchBox.y + touchBox.height / 2 };
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [touchPoint] });
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchPoint.x + 20, y: touchPoint.y + 15 }] });
    assert.equal(await hit.getAttribute('data-dragging'), 'true');
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    assert.equal(await hit.getAttribute('data-dragging'), 'false');
    await page.getByLabel('Force Reduced Motion').check();
    await page.getByLabel('Force Reduced Motion').uncheck();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.waitForTimeout(100);
    const systemFrames = await orb.getAttribute('data-frame');
    await page.waitForTimeout(150);
    assert.equal(await orb.getAttribute('data-frame'), systemFrames);
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    // Direct canonical runtime: deterministic state and input lifecycle checks.
    await page.mouse.move(5, 5);
    await page.mouse.down();
    const runtime = await page.evaluate(async () => {
      const { createOrb } = await import('/src/components/ai/interactive-orb/renderer.js');
      const host = document.createElement('div');
      host.className = 'orb3d';
      host.style.width = '192px';
      const cap = document.createElement('div');
      cap.innerHTML = '<svg><path d="M2 10 12 5 22 10 12 15Z"/></svg>';
      const aura = document.createElement('div'), shadow = document.createElement('div'), hit = document.createElement('button');
      host.append(cap, aura, shadow, hit);
      document.body.append(host);
      const renderer = createOrb(host, 3, cap, aura, shadow, hit);
      const canvas = host.querySelector('canvas');
      const initial = renderer.state();
      renderer.configure({ applicationState: 'thinking' });
      renderer.draw(.1);
      const transition = renderer.state();
      renderer.draw(1);
      const thinking = renderer.state();
      renderer.configure({ quality: 'low' });
      const low = renderer.state();
      renderer.configure({ quality: 'medium' });
      const medium = renderer.state();
      renderer.configure({ quality: 'high', applicationState: 'idle' });
      renderer.draw(2);
      hit.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowLeft', bubbles: true }));
      renderer.draw(2.1);
      const keyboard = renderer.state();
      hit.dispatchEvent(new PointerEvent('pointerdown', { pointerId: 1, isPrimary: true, button: 0, clientX: 20, clientY: 20 }));
      hit.dispatchEvent(new PointerEvent('pointermove', { pointerId: 1, isPrimary: true, clientX: 50, clientY: 40 }));
      const dragging = renderer.state();
      hit.dispatchEvent(new PointerEvent('pointercancel', { pointerId: 1 }));
      const cancelled = renderer.state();
      hit.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight' }));
      renderer.draw(3);
      const momentum = renderer.state();
      renderer.draw(3.5);
      const friction = renderer.state();
      renderer.reset(); renderer.draw(4.3);
      const reset = renderer.state();
      renderer.draw(5, true);
      const reduced = renderer.state();
      renderer.draw(6, true);
      const still = renderer.state();
      const sameCanvas = canvas === host.querySelector('canvas');
      renderer.dispose();
      const disposed = host.querySelectorAll('canvas').length;
      hit.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowLeft' }));
      const afterDispose = renderer.state();
      host.remove();
      return { initial, transition, thinking, low, medium, keyboard, dragging, cancelled, momentum, friction, reset, reduced, still, sameCanvas, disposed, afterDispose };
    });
    await page.mouse.up();
    assert.equal(runtime.initial.energy, 1);
    assert.equal(runtime.initial.quality, 'high');
    assert.ok(runtime.transition.energy > 1 && runtime.transition.energy < 1.22);
    assert.equal(runtime.thinking.amber, 0);
    assert.equal(runtime.low.dpr, 1);
    assert.equal(runtime.medium.dpr, Math.min(await page.evaluate(() => window.devicePixelRatio), 1.25));
    assert.ok(runtime.keyboard.speed > 0);
    assert.equal(runtime.dragging.dragging, true);
    assert.equal(runtime.cancelled.dragging, false);
    assert.equal(runtime.cancelled.speed, 0);
    assert.ok(runtime.friction.speed < runtime.momentum.speed);
    assert.equal(runtime.reset.resetting, false);
    assert.ok(Math.abs(runtime.reset.orientation[3] - 1) < .0001);
    assert.equal(runtime.reduced.speed, 0);
    assert.equal(runtime.still.orbitTime, runtime.reduced.orbitTime);
    assert.deepEqual(runtime.still.orientation, runtime.reduced.orientation);
    assert.equal(runtime.sameCanvas, true);
    assert.equal(runtime.disposed, 0);
    assert.equal(runtime.afterDispose.speed, 0);
    report.runtime = runtime;
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.goto(origin + 'motion-preview-3d/');
    await page.waitForFunction(() => window.motion3d?.states().length === 5);
    await page.screenshot({ path: evidence + 'motion-preview-3d.png', fullPage: true });
    assert.equal((await page.evaluate(() => window.motion3d.states())).length, 5);
    await page.goto(origin + 'shaheen-lab');
    await page.waitForFunction(() => document.querySelector('.orb3d')?.dataset.ready === 'true');
    await page.locator('.orb3d canvas').evaluate(canvas => canvas.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());
    await page.waitForFunction(() => document.querySelector('.orb3d')?.dataset.failed === 'true');
    assert.equal(await page.locator('.orb-static-fallback').count(), 1);
    await page.screenshot({ path: evidence + 'webgl-fallback.png' });
    await page.goto(origin + 'login');
    assert.equal(await page.locator('.orb3d canvas').count(), 0);
    assert.deepEqual(errors, []);
    await writeFile(evidence + 'measurements.json', JSON.stringify(report, null, 2));
  } finally { await browser.close(); await server.close(); }
});

test('Lab is development guarded and absent from main navigation', async () => {
  const app = await readFile(new URL('../src/App.tsx', import.meta.url), 'utf8');
  assert.match(app, /import\.meta\.env\.DEV \? <Route path="\/shaheen-lab"/);
  for (const path of ['Sidebar.tsx', 'Header.tsx']) assert.doesNotMatch(await readFile(new URL('../src/components/layout/' + path, import.meta.url), 'utf8'), /shaheen-lab/);
});
