import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '../../..');
const { chromium } = createRequire(path.join(root, 'scratch/video-production/package.json'))('playwright-core');
const sharp = createRequire(path.join(root, 'artifacts/university-app/package.json'))('sharp');
test('pointer rotation, inertia, reset, cap modes and focused keyboard control', { timeout: 90000 }, async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, hasTouch: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto('http://localhost:5173/motion-preview-3d/', { waitUntil: 'networkidle' });
    const region = page.getByRole('button', { name: 'Interactive 3D orb', exact: true });
    assert.equal(await region.count(), 1, 'Interactive focused rotation region must exist');
    await region.scrollIntoViewIfNeeded();
    await page.getByRole('checkbox', { name: 'Idle Rotation' }).uncheck();
    await page.getByRole('checkbox', { name: 'Orbit Motion' }).uncheck();
    await page.getByRole('checkbox', { name: 'Particle Motion' }).uncheck();
    const state = () => page.evaluate(() => window.motion3d.states().find(state => state.interactive));
    const frame = time => page.evaluate(time => window.motion3d.frame(time, 'interactive'), time);
    await frame(0);
    await region.scrollIntoViewIfNeeded();
    const box = await region.boundingBox();
    const x = box.x + box.width / 2;
    const y = box.y + box.height / 2;
    const before = await state();
    const faceBefore = await sharp(await region.screenshot()).removeAlpha().raw().toBuffer();
    await page.mouse.move(x, y);
    await page.mouse.down();
    assert.equal(await region.evaluate(el => getComputedStyle(el).cursor), 'grabbing');
    await frame(.04);
    await page.mouse.move(x - 50, y - 35);
    const dragged = await state();
    const faceAfter = await sharp(await region.screenshot()).removeAlpha().raw().toBuffer();
    let difference = 0;
    for (let i = 0; i < faceBefore.length; i++) difference += Math.abs(faceBefore[i] - faceAfter[i]);
    const meanRotationPixelChange = difference / faceBefore.length;
    assert.ok(meanRotationPixelChange > 1, 'Manual rotation must visibly reveal different surface information');
    assert.notDeepEqual(dragged.orientation, before.orientation, 'Diagonal pointer drag must change 3D orientation');
    assert.ok(Math.abs(dragged.orientation[0]) > .01 && Math.abs(dragged.orientation[1]) > .01, 'Both X and Y axes must rotate');
    assert.ok(dragged.speed <= 2.2, 'Angular momentum must be capped');
    const afterBox = await region.boundingBox();
    assert.deepEqual(afterBox, box, 'The object stays centered');
    await frame(.06);
    await page.mouse.move(x - 54, y - 37);
    await page.mouse.up();
    await frame(.14);
    const coast = await state();
    assert.notDeepEqual(coast.orientation, dragged.orientation, 'Released pointer must retain momentum');
    await frame(1.5);
    assert.ok((await state()).speed < coast.speed, 'Momentum must damp');
    assert.equal((await state()).orbitTime, before.orbitTime, 'Orbit OFF freezes its independent clock');
    assert.equal((await state()).particleTime, before.particleTime, 'Particle OFF freezes its independent clock');
    const frozen = await state();
    await page.locator('header h1').click();
    await page.keyboard.press('ArrowLeft');
    await frame(2.5);
    assert.ok((await state()).speed < .02, 'Unfocused arrow keys must not start rotation');
    await region.focus();
    await page.keyboard.press('ArrowUp');
    await frame(2.65);
    assert.notDeepEqual((await state()).orientation, frozen.orientation, 'Focused keyboard input rotates the sphere');
    await page.keyboard.press('r');
    const resetStart = await state();
    assert.ok(resetStart.resetting, 'Reset must animate');
    await frame(3.05);
    assert.notDeepEqual((await state()).orientation, resetStart.orientation, 'Reset interpolates before completion');
    await frame(3.5);
    assert.ok((await state()).orientation.slice(0, 3).every(value => Math.abs(value) < .001), 'Reset ends at default orientation');
    await page.getByRole('radio', { name: 'Cap follows sphere' }).check();
    assert.equal((await state()).capMode, 'surface');
    await page.getByRole('radio', { name: 'Cap faces camera' }).check();
    assert.equal((await state()).capMode, 'camera');
    await region.focus();
    await page.waitForFunction(() => window.motion3d.states().find(state => state.interactive).idleEnabled === false);
    await page.keyboard.press('Space');
    await page.waitForFunction(() => document.querySelector('.prototype-controls input[type="checkbox"]').checked === true);
    assert.equal((await state()).idleEnabled, true, 'Space toggles idle only in the focused region');
    await page.keyboard.press('Space');
    await page.waitForFunction(() => document.querySelector('.prototype-controls input[type="checkbox"]').checked === false);
    assert.equal(await page.getByRole('checkbox', { name: 'Idle Rotation' }).isChecked(), false);
    await page.getByRole('checkbox', { name: 'Idle Rotation' }).check();
    await frame(5);
    await frame(6);
    assert.ok((await state()).idleBlend > .8, 'Idle rotation blends back after a calm period');
    await page.getByRole('checkbox', { name: 'Orbit Motion' }).check();
    await page.getByRole('checkbox', { name: 'Particle Motion' }).check();
    await frame(6.2);
    assert.ok((await state()).orbitTime > before.orbitTime && (await state()).particleTime > before.particleTime, 'Each independent clock resumes');
    const touchBefore = await state();
    const touchSession = await page.context().newCDPSession(page);
    const touchBox = await region.boundingBox();
    const tx = touchBox.x + touchBox.width / 2;
    const ty = touchBox.y + touchBox.height / 2;
    const scrollBefore = await page.evaluate(() => scrollY);
    await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: tx, y: ty }] });
    await frame(6.24);
    await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: tx + 30, y: ty - 40 }] });
    await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    assert.notDeepEqual((await state()).orientation, touchBefore.orientation, 'One-finger touch rotates actual geometry');
    assert.equal(await page.evaluate(() => scrollY), scrollBefore, 'A drag starting inside the orb does not scroll');
    assert.equal(await region.evaluate(el => getComputedStyle(el).touchAction), 'none');
    assert.notEqual(await page.locator('main').evaluate(el => getComputedStyle(el).touchAction), 'none', 'Page scrolling outside the orb stays enabled');
    await touchSession.detach();
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await region.focus();
    await page.keyboard.press('ArrowLeft');
    await frame(7);
    const reduced = await state();
    await frame(9);
    assert.deepEqual((await state()).orientation, reduced.orientation, 'Reduced motion disables automatic movement/inertia');
    assert.deepEqual(errors, []);
    const output = path.join(root, 'artifacts/video/ai-orb-interactive-3d-study');
    await mkdir(output, { recursive: true });
    await writeFile(path.join(output, 'interaction-verification.json'), JSON.stringify({ passed: true, pointerAndTouch: true,
      inertiaAndDamping: true, centered: true, focusedKeyboardOnly: true, capModes: true, smoothReset: true,
      independentSwitches: true, idleResume: true, reducedMotion: true, meanRotationPixelChange }, null, 2));
  } finally { await browser.close(); }
});
